	# Contenido del fichero env.sh
	export CLUSTER_NAME="nkp-mgmt" # Name of the Kubernetes cluster 
	export NUTANIX_PC_FQDN_ENDPOINT_WITH_PORT="https://10.48.70.5:9440" # Nutanix Prism Central endpoint URL with port 
	export CONTROL_PLANE_IP="10.48.108.5" # IP address for the Kubernetes control plane 
	export IMAGE_NAME="nkp-rocky-9.5-release-cis-1.30.5-20241204003513.qcow2" # Name of the VM image to use for cluster nodes 
	export PRISM_ELEMENT_CLUSTER_NAME="Trevor-1" # Name of the Nutanix Prism Element cluster 
	export SUBNET_NAME="kubernetes" # Name of the subnet to use for cluster nodes 
	export PROJECT_NAME="Default" # Name of the Nutanix project 
	export CONTROL_PLANE_REPLICAS="3" # Number of control plane replicas 
	export CONTROL_PLANE_VCPUS="4" # Number of vCPUs for control plane nodes 
	export CONTROL_PLANE_CORES_PER_VCPU="1" # Number of cores per vCPU for control plane nodes 
	export CONTROL_PLANE_MEMORY_GIB="16" # Memory in GiB for control plane nodes 
	export WORKER_REPLICAS="3" # Number of worker node replicas 
	export WORKER_VCPUS="8" # Number of vCPUs for worker nodes 
	export WORKER_CORES_PER_VCPU="1" # Number of cores per vCPU for worker nodes 
	export WORKER_MEMORY_GIB="32" # Memory in GiB for worker nodes 
	export NUTANIX_STORAGE_CONTAINER_NAME="default container" # Name of the Nutanix storage container 
	export CSI_FILESYSTEM="ext4" # Filesystem type for CSI volumes 
	export CSI_HYPERVISOR_ATTACHED="true" # Whether to use hypervisor-attached volumes for CSI 
	export LB_IP_RANGE="10.48.108.6-10.48.108.10" # IP range for load balancer services 
	export SSH_KEY_FILE="/root/.ssh/id_rsa.pub" # Path to the SSH public key file 
	export NUTANIX_USER="root" # Nutanix PrismCentral username (left blank for security) 
	export NUTANIX_PASSWORD="" # Nutanix PrismCentral password (left blank for security) 
	export REGISTRY_URL="https://10.48.71.202/dockerhub" # URL for the private container registry "http://registry_IP:5000" in docker use case 
	export REGISTRY_USERNAME="admin" # Username for authenticating with the private registry (left blank for security) 
	export REGISTRY_PASSWORD="" # Password for authenticating with the private registry (left blank for security) 
	export REGISTRY_CA="/root/certs/server.crt" # Path to the CA certificate for the private registry
	export INGRESS_CERT="/home/administrator/certs/nkp-lab.domain.local/nkp-lab-domain.local.cert" # Path to the cert of ingress (opt)
	export INGRESS_KEY="/home/administrator/certs/nkp-lab.domain.local/nkp-lab-domain.local.key" # Path to the .key file of the ingress cert (opt)
	export INGRESS_CA="/home/administrator/certs/ca-chain.cert" # Path to the ingress CA-chain file (opt)
	export INGRESS_FQDN="nkp-lab.domain.local" #FQDN of the Ingress controller to be used for browsing NKP web GUI (opt)
	export DOCKER_REGISTRY="https://joho-registry.domain.local/dockerhub" # URL To Pulltrough Cache for docker images
